Repository line/line-bot-sdk-php, pull requests merged in 2018-10, with the labels that each got.

#174 change thumbnailImageUrl and title are optional params
  src/LINEBot/MessageBuilder/TemplateBuilder/ButtonTemplateBuilder.php
  tests/LINEBot/MessageBuilder/TemplateBuilder/ButtonTemplateBuilderTest.php
Labels: bug

#185 Support raw message builder
  src/LINEBot/MessageBuilder/RawMessageBuilder.php
  tests/LINEBot/SendFlexTest.php
Labels: enhancement

#187 Fix curl get params handling
  src/LINEBot/HTTPClient.php
  src/LINEBot/HTTPClient/CurlHTTPClient.php
  tests/LINEBot/HTTPClient/CurlHTTPClientTest.php
Labels: bug

#177 Changed LocationMessage for message without title or address key
  src/LINEBot/Event/MessageEvent/LocationMessage.php
  tests/LINEBot/EventRequestParserTest.php
Labels: bug

#188 Support AccountLink event
  examples/KitchenSink/src/LINEBot/KitchenSink/EventHandler/AccountLinkEventHandler.php
  examples/KitchenSink/src/LINEBot/KitchenSink/Route.php
  src/LINEBot/Event/AccountLinkEvent.php
  src/LINEBot/Event/Parser/EventRequestParser.php
  tests/LINEBot/EventRequestParserTest.php
Labels: missing function
